spring:
  main:
    web-application-type : REACTIVE
  application:
    name: openia
  ai:
    openai:
      api-key: <Cole sua chave aqui o site ta no README>
      api-url: https://api.openai.com/v1/chat/completions
      chat:
        options:
          model: gpt-4o-mini
  openia:
    title: 'Pergunte ao meu OvO.'
    version: 'MELANCIA 01'
    description: 'Faça perguntas ao meu OvO e vê o que ele te responde.'
    name: 'Tigão DESSS'
    email: 'micheltiago@hotmail.com'